### ISSUE TITLE
Does not work with with latest version of `jrnl` (2.0.1)

### ISSUE THREAD

**Issue by thanateros** [Hatoris/taskwarrior_jrnl_hook#1]
`jrnl` stores its config in `YAML` now.

When I point `jrnl_config` to the new YAML format config file, I get **JSONDecodeError** because it is trying to parse a YAML as a JSON file.

I like the idea of this project and am looking for a way to use `jrnl` with `taskwarrior`; this would have been great except that it doesn't work.

Can we get it to work? I'm no Python expert or I would try to fix it myself.

**Comment by Hatoris** [comment]
Hello thanateros, 

This commit should do the job https://github.com/Hatoris/taskwarrior_jrnl_hook/commit/5ef5f395f4c240e32c49f1ac2fa00798a498617d. 

Could you please run `pip install taskwarrior-jrnl-hook --upgrade` then don't forget to symilink the script : 

`ln -s ~/.local/bin/taskwarrior_jrnl_hook ~/.task/hooks/on-modify.jrnl`

Did this commit solve your issue ?

**Comment by thanateros** [comment]
I assumed the `pip install pip install` needed to just be `pip install`.

I'm using Python 3, so I used pip3 instead (hope that doesn't make a difference).

The upgraded was successful. I removed the old symlink and rebuilt it according to your instructions.

In my `~/.taskrc`, I had already added the line `jrnl_config=~/.config/jrnl/jrnl.yaml` (where jrnl puts my config file by default).

I started a task in taskwarrior and now I get this error:

```bash
$ task 1 start
[task 1 start]
/home/[myusername]/.local/lib/python3.7/site-packages/taskwarrior_jrnl_hook/__init__.py:45: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  JRNL_CONFIG = yaml.load(f)
Traceback (most recent call last):
  File "/home/[myusername]/.task/hooks/on-modify.jrnl", line 6, in <module>
    from taskwarrior_jrnl_hook import cmdline
  File "/home/[myusername]/.local/lib/python3.7/site-packages/taskwarrior_jrnl_hook/__init__.py", line 46, in <module>
    TAGS_SYMBOL = JRNL_CONFIG.get("tagsymbols", "@")
AttributeError: 'NoneType' object has no attribute 'get'
Hook Error: Expected feedback from a failing hook script.
```

Am I doing something wrong?

Versions:
- Python: 3.7.3
- OS: Ubuntu 19.04 Server
- Taskwarrior: 2.5.1
- jrnl: 2.0.1

**Comment by thanateros** [comment]
Oh, and I have encryption enabled, if that makes a difference.

**Comment by Hatoris** [comment]
You did nothing wrong. I found why this error happend, I know a way to patch this issue but I found the clean way to do it.

[If you are curious](https://stackoverflow.com/questions/58664017/why-catching-an-exception-close-the-open-file-with-and-without-context)

**Comment by Hatoris** [comment]
Could you please upgrade again the package and test it ?

**Comment by thanateros** [comment]
Yes, have to wait for when I get home later.

**Comment by thanateros** [comment]
It works! Thanks!
